### ISSUE TITLE
the template has admin value

### ISSUE THREAD

**Issue by cookie33** [sara-nl/irods-msi-persistent-id#3]
The template_2 has the value:
```
    "admin": "0.NA",
```

It would be better if it is either:
```
"admin": "0.NA/{HANDLE_PREFIX}"
```

or

remove `admin` and make it in the json tree:
```
              "handle": "0.NA/{HANDLE_PREFIX}",
```

**Comment by stefan-wolfsheimer** [comment]
There is a reason for the additional admin field.

- "admin": "0.NA/{HANDLE_PREFIX}": this option will not work because the macros are only resolved inside the handle profile

- "handle": "0.NA/{HANDLE_PREFIX}": this option would work technically for the non-default template (with explicit profile). However, if you want to use the default profile, the admin value field is not editable. By configuring the admin value in the general  handle section, it is straightforward to switch between different profiles, including the default template.
